# Generated by Django 4.0.5 on 2022-06-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraEntregaFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deportes',
            new_name='Deporte',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
        migrations.RenameModel(
            old_name='Socios',
            new_name='Socio',
        ),
    ]
