# Generated by Django 4.0.5 on 2022-06-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraEntregaFinalApp', '0002_rename_deportes_deporte_rename_profesores_profesor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administracion',
            new_name='Administrador',
        ),
    ]
