# Generated by Django 4.0.5 on 2022-06-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraEntregaFinalApp', '0003_rename_administracion_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='horarios',
        ),
        migrations.AddField(
            model_name='deporte',
            name='horario',
            field=models.CharField(default='Some String', max_length=60),
        ),
    ]
