# Generated by Django 4.0.5 on 2022-06-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraEntregaFinalApp', '0004_remove_deporte_horarios_deporte_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='deporte',
            name='horario',
            field=models.CharField(default='Sin horario', max_length=60),
        ),
    ]
